club/urls.py
from django.urls import path
from .views import ClubView

app_name = "club"

urlpatterns = [
  path('', ClubView.as_view(), name="home")
]

common/urls.py
from django.urls import path
from .views import HomeView

app_name = "common"

urlpatterns = [
    path('', HomeView.as_view(), name="home")
]

mcg/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('', include('common.urls')),
    path('admin/', admin.site.urls),
    path('members/', include('members.urls')),
    path('club/', include('club.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.urls import path
from .views import CustomLoginView, CustomLogoutView, SignUpView, CustomUserListView

app_name = 'members'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('list/', CustomUserListView.as_view(), name='list')
]

blog/models.py
from django.db import models

# Create your models here.

club/models.py
from django.db import models
from members.models import CustomUser
from django.utils.translation import gettext_lazy as _
from common.models import TimeStampedModel

# Create your models here.

class CashRegister(TimeStampedModel):
  name = models.CharField(max_length=150, blank=False, null=True, verbose_name=_("Nom"))
  current_balance = models.DecimalField(max_digits=5, decimal_places=2)

  class Meta:
    verbose_name = _("Caisse")
    verbose_name_plural = _("Caisses")

class Reason(models.Model):

  TRANSACTION_TYPE = [
    ('debit', 'Débit'),
    ('credit', 'Crédit')
  ]

  name = models.CharField(max_length=150, blank=False, null=True, verbose_name=_("Nom"))
  transaction_type = models.CharField(max_length=10, choices=TRANSACTION_TYPE, null=True, verbose_name=_("Opération"))

  class Meta:
    verbose_name = _("Motif")
    verbose_name_plural = _("Motifs")


class Transaction(TimeStampedModel):
  amount = models.DecimalField(max_digits=5, decimal_places=2)
  user = models.ForeignKey(CustomUser, on_delete=models.PROTECT, null=True, verbose_name="Membre")
  reason = models.ForeignKey(Reason, on_delete=models.PROTECT, null=True, verbose_name="Motif")

  class Meta:
    verbose_name = _("Transaction")
    verbose_name_plural = _("Transactions")

common/models.py
from django.db import models

class TimeStampedModel(models.Model):
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  class Meta:
      abstract = True
      ordering = ["-updated_at"]
      get_latest_by = "-updated_at"

members/models.py
from datetime import date
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from common import fields as common_field
from django.contrib.postgres import fields as postgres_field
from .validators import validate_contact
from django.utils import timezone
from django.contrib import admin
from django.utils.translation import gettext_lazy as _

def get_photo_path(self, filename):
	file_extension = filename.split('.')[-1]
	instance_id = self.pk
	return f"img/members/user_{instance_id}.{file_extension}"

class CustomUserManager(BaseUserManager):
	def _create_user(self, email, password, **extra_fields):
		if not email:
				raise ValueError("The given email must be set")
		
		email = self.normalize_email(email)
		user = self.model(email=email, **extra_fields)
		user.set_password(password)
		user.save(using=self._db)
		return user
	
	def create_user(self, email, password, **extra_fields):
		last_name = extra_fields.get("last_name")
		first_name = extra_fields.get("first_name")
		username = f"{last_name[0].upper()}.{first_name.capitalize()}"
		extra_fields.setdefault("is_active", False)
		extra_fields.setdefault("is_staff", False)
		extra_fields.setdefault("is_superuser", False)
		extra_fields.setdefault("username", username)
		return self._create_user(email, password, **extra_fields)

	def create_superuser(self, email, password, **extra_fields):
		extra_fields.setdefault("is_staff", True)
		extra_fields.setdefault("is_superuser", True)

		if extra_fields.get("is_staff") is not True:
				raise ValueError("Superuser must have is_staff=True.")
		if extra_fields.get("is_superuser") is not True:
				raise ValueError("Superuser must have is_superuser=True.")

		return self._create_user(email, password, **extra_fields)

class CustomUser(AbstractUser):

	DEFAULT_PHOTO = 'img/anonymous.png'
	GENDER = [('homme', 'Homme'), ('femme', 'Femme')]

	username = models.CharField(max_length=150, unique=True, blank=True, null=True, verbose_name="Nom d'utilisateur")
	email = models.EmailField(max_length=250, unique=True, blank=False, verbose_name=_("Email"))
	last_name = common_field.CustomCharField(max_length=150, blank=False, uppercase=True, verbose_name="Nom")
	first_name = common_field.CustomCharField(max_length=150, blank=False, capitalcase=True, verbose_name="Prénoms")
	photo = models.ImageField(default=DEFAULT_PHOTO, upload_to=get_photo_path, null=True, verbose_name="Photo")
	birthday = models.DateField(blank=False, null=True, verbose_name="Date de naissance")
	gender = models.CharField(max_length=10, choices=GENDER, null=True, verbose_name="Sexe")
	date_joined = models.DateTimeField(default=timezone.now, verbose_name="Date d'adhésion")
	description = models.TextField(max_length=250, blank=True, null=True, verbose_name=_("Description"))
	contacts = postgres_field.ArrayField(
		base_field=models.CharField(max_length=10, blank=False, null=False, unique=True, validators=[validate_contact], verbose_name="Téléphone"),
		size=3
	)
	is_active = models.BooleanField(default=True, verbose_name="Compte Activé")
	is_staff = models.BooleanField(default=False, verbose_name="Membre du bureau")
	is_superuser = models.BooleanField(default=False)
	
	class Meta:
		verbose_name = _("User")
		verbose_name_plural = _("Users")
		ordering = ['-date_joined',]
		constraints = [
			models.UniqueConstraint(
				fields=('last_name', 'first_name'), name='name_unique'),
		]

	objects = CustomUserManager()
	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = ['last_name', 'first_name', 'gender', 'contacts']

	@admin.display(description="Age")
	def get_user_age(self)->int:
		if self.birthday is not None:
			return date.today().year - self.birthday.year
		return 0	

	def __str__(self):
		return f"{self.last_name}, {self.first_name}"

members/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser
from django.contrib.postgres import forms as postgres_form

class CustomUserCreationForm(UserCreationForm):
  birthday = forms.DateField(
    widget=forms.DateInput(
      attrs={
        'type': 'date'
      }
    )
  )

  contacts = postgres_form.SplitArrayField(
    forms.CharField(max_length=10),
    size=3
  )
  class Meta:
    model = CustomUser
    fields = ('photo', 'email', 'password1', 'password2', 'last_name', 'first_name', 'gender', 'birthday', 'contacts')
    exclude = ('username',)

club/views.py
from django.shortcuts import render
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy


# Create your views here.

class ClubView(LoginRequiredMixin, View):
    login_url = reverse_lazy("members:login")
    def get(self, request):
        context = {
            "user": request.user
        }
        return render(request, 'club/home.html', context=context)
    

common/views.py
from django.shortcuts import render
from django.views import generic

# Create your views here.
class HomeView(generic.View):
    def get(self, request):
        return render(request, 'common/home.html')
    

members/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.views import generic
from .forms import CustomUserCreationForm
from .models import CustomUser

# NOTE :
# With CustomUserBackend we can use form.username as email field in login template
# No need to override AuthenticationForm
class CustomLoginView(LoginView):
  template_name = "members/login.html"

class CustomLogoutView(LogoutView):
  template_name = "members/logged_out.html"

class SignUpView(generic.CreateView):
  form_class = CustomUserCreationForm
  model = CustomUser
  success_url = reverse_lazy("members:login")
  template_name = "members/signup.html"

  def form_valid(self, form):
    last_name = form.instance.last_name
    first_name = form.instance.first_name
    form.instance.username = f"{last_name[0].upper()}.{first_name.capitalize()}"
    return super().form_valid(form)
  
class CustomUserListView(generic.ListView):
  model = CustomUser
  paginate_by = 12

club/templates/club/header.html
{% load static %}

<nav class="fixed top-0 z-50 w-full bg-white border-b border-gray-200 dark:bg-gray-800 dark:border-gray-700">
  <div class="px-3 py-3 lg:px-5 lg:pl-3">
    <div class="flex items-center justify-between">
      <div class="flex items-center justify-start rtl:justify-end">
        <button data-drawer-target="logo-sidebar" data-drawer-toggle="logo-sidebar" aria-controls="logo-sidebar" type="button" class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg sm:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600">
            <span class="sr-only">Open sidebar</span>
            <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
               <path clip-rule="evenodd" fill-rule="evenodd" d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z"></path>
            </svg>
         </button>
         
        <a href="{% url "common:home" %}" class="flex w-12 h-12 bg-blue-500 rounded-full">
            <img src="{% static 'img/logo.png' %}" class="h-14" alt="MCG Logo">
            <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">MCG</span>
        </a>
      </div>
      <div class="flex items-center">
          <div class="flex items-center ms-3">
            <div>
              <button type="button" class="flex items-center justify-center w-12 h-12 bg-blue-500 rounded-full" aria-expanded="false" data-dropdown-toggle="dropdown-user">
                <span class="sr-only">Open user menu</span>
                <span class="text-white text-xl font-bold">{{ user.username|first }}</span>
              </button>
            </div>
            <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded shadow dark:bg-gray-700 dark:divide-gray-600" id="dropdown-user">
              <div class="px-4 py-3" role="none">
                <p class="text-sm text-gray-900 dark:text-white" role="none">
                  {{ user.username }}
                </p>
                <p class="text-sm font-medium text-gray-900 truncate dark:text-gray-300" role="none">
                  {{ user.email }}
                </p>
              </div>
              <ul class="py-1" role="none">
                <li>
                  <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Dashboard</a>
                </li>
                <li>
                  <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Settings</a>
                </li>
                <li>
                  <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Earnings</a>
                </li>
                <li>
                  <a href="{% url "members:logout" %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Sign out</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
    </div>
  </div>
</nav>

common/templates/common/footer.html
{% load static %}

<footer class="p-4 bg-white sm:p-6 dark:bg-gray-800">
    <div class="mx-auto max-w-screen-xl">
        <div class="md:flex md:justify-between">
            <div class="mb-6 md:mb-0">
                <a href="https://flowbite.com" class="flex items-center">
                    <img src="{% static 'img/logo.png' %}" class="mr-3 h-8" alt="FlowBite Logo" />
                    <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">MCG</span>
                </a>
            </div>
            <div class="grid grid-cols-2 gap-8 sm:gap-6 sm:grid-cols-3">
                <div>
                    <h2 class="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-white">Coordonnées</h2>
                    <ul class="text-gray-600 dark:text-gray-400">
                        <li class="mb-4">
                            <a href="https://maps.app.goo.gl/VARR4VkDQ7ywvV2p7" class="inline-flex hover:underline ">
                                <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                                    <path fill-rule="evenodd" d="M11.906 1.994a8.002 8.002 0 0 1 8.09 8.421 7.996 7.996 0 0 1-1.297 3.957.996.996 0 0 1-.133.204l-.108.129c-.178.243-.37.477-.573.699l-5.112 6.224a1 1 0 0 1-1.545 0L5.982 15.26l-.002-.002a18.146 18.146 0 0 1-.309-.38l-.133-.163a.999.999 0 0 1-.13-.202 7.995 7.995 0 0 1 6.498-12.518ZM15 9.997a3 3 0 1 1-5.999 0 3 3 0 0 1 5.999 0Z" clip-rule="evenodd"/>
                                  </svg>                                  
                                <span>Institut ISS</span>
                            </a>
                        </li>
                        <li class="mb-4">
                            <a href="" class="inline-flex hover:underline ">
                                <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                                    <path d="M7.978 4a2.553 2.553 0 0 0-1.926.877C4.233 6.7 3.699 8.751 4.153 10.814c.44 1.995 1.778 3.893 3.456 5.572 1.68 1.679 3.577 3.018 5.57 3.459 2.062.456 4.115-.073 5.94-1.885a2.556 2.556 0 0 0 .001-3.861l-1.21-1.21a2.689 2.689 0 0 0-3.802 0l-.617.618a.806.806 0 0 1-1.14 0l-1.854-1.855a.807.807 0 0 1 0-1.14l.618-.62a2.692 2.692 0 0 0 0-3.803l-1.21-1.211A2.555 2.555 0 0 0 7.978 4Z"/>
                                  </svg>                                  
                                <span>034 36 457 86</span>
                            </a>
                        </li>
                    </ul>
                </div>
                <div>
                    <h2 class="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-white">Suivez-nous</h2>
                    <ul class="text-gray-600 dark:text-gray-400">
                        <li class="mb-4">
                            <a href="https://lichess.org/team/mcg-club" class="inline-flex hover:underline ">
                                <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                                    <path fill-rule="evenodd" d="M12 6a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7Zm-1.5 8a4 4 0 0 0-4 4 2 2 0 0 0 2 2h7a2 2 0 0 0 2-2 4 4 0 0 0-4-4h-3Zm6.82-3.096a5.51 5.51 0 0 0-2.797-6.293 3.5 3.5 0 1 1 2.796 6.292ZM19.5 18h.5a2 2 0 0 0 2-2 4 4 0 0 0-4-4h-1.1a5.503 5.503 0 0 1-.471.762A5.998 5.998 0 0 1 19.5 18ZM4 7.5a3.5 3.5 0 0 1 5.477-2.889 5.5 5.5 0 0 0-2.796 6.293A3.501 3.501 0 0 1 4 7.5ZM7.1 12H6a4 4 0 0 0-4 4 2 2 0 0 0 2 2h.5a5.998 5.998 0 0 1 3.071-5.238A5.505 5.505 0 0 1 7.1 12Z" clip-rule="evenodd"/>
                                </svg>                                                                 
                                <span>Equipe Lichess</span>
                            </a>
                        </li>
                        <li class="mb-4">
                            <a href="https://web.facebook.com/malagasychessgameMCG" class="inline-flex hover:underline ">
                                <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                                    <path fill-rule="evenodd" d="M13.135 6H15V3h-1.865a4.147 4.147 0 0 0-4.142 4.142V9H7v3h2v9.938h3V12h2.021l.592-3H12V6.591A.6.6 0 0 1 12.592 6h.543Z" clip-rule="evenodd"/>
                                </svg>
                                <span>Malagasy Chess Game</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <hr class="my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8" />
        <div class="sm:flex sm:items-center sm:justify-between">
            <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2024 <a href="#" class="hover:underline">Malagasy Chess Game</a>. All Rights Reserved.
            </span>
        </div>
    </div>
</footer>

common/templates/common/header.html
{% load static %}

<nav class="bg-white dark:bg-gray-900 fixed w-full z-20 top-0 start-0 border-b border-gray-200 dark:border-gray-600">
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
        <a href="{% url "common:home" %}" class="flex items-center space-x-3 rtl:space-x-reverse">
            <img src="{% static 'img/logo.png' %}" class="h-14" alt="MCG Logo">
            <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">MCG</span>
        </a>
        <div class="flex md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
            {% if request.user.is_authenticated %}
                <button type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"><a href="{% url "members:logout" %}">Se déconnecter</a></button>
            {% else %}
                <button type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"><a href="{% url "members:login" %}">Se connecter</a></button>
            {% endif %}
            <button data-collapse-toggle="navbar-sticky" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-sticky" aria-expanded="false">
                <span class="sr-only">Open main menu</span>
                <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
                </svg>
            </button>
        </div>
        <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-sticky" 
        x-data="{ current_page: localStorage.getItem('activeTab') || 'Acceuil',
                  clicked_style: 'block py-2 px-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 md:dark:text-blue-500',
                  no_clicked_style: 'block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700' }">
        <ul class="flex flex-col p-4 md:p-0 mt-4 font-medium border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
            <li>
                <a href="{% url "common:home" %}" x-on:click="current_page = 'Acceuil'; localStorage.setItem('activeTab', 'Acceuil')" x-bind:class="current_page === 'Acceuil' ? clicked_style : no_clicked_style">Acceuil</a>
            </li>
            <li>
                <a href="#" x-on:click="current_page = 'Blog'; localStorage.setItem('activeTab', 'Blog')" x-bind:class="current_page === 'Blog' ? clicked_style : no_clicked_style">Blog</a>
            </li>
            <li>
                <a href="{% url "members:list" %}" x-on:click="current_page = 'Membres'; localStorage.setItem('activeTab', 'Membres')" x-bind:class="current_page === 'Membres' ? clicked_style : no_clicked_style">Membres</a>
            </li>
            <li>
                <a href="#" x-on:click="current_page = 'Contact'; localStorage.setItem('activeTab', 'Contact')" x-bind:class="current_page === 'Contact' ? clicked_style : no_clicked_style">Contact</a>
            </li>
        </ul>
    </div>
    
    </div>
</nav>

members/templates/members/login.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% load static %}

{% block content %}
<section class="bg-gray-50 dark:bg-gray-900">
    <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
        <a href="{% url "common:home" %}" class="flex items-center mb-6 text-2xl font-semibold text-gray-900 dark:text-white">
            <img class="w-12 h-12 mr-2" src="{% static 'img/logo.png' %}" alt="logo">
            Malagasy Chess Game    
        </a>
        <div class="w-full max-w-sm p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700">
            <h5 class="text-xl font-medium text-gray-900 dark:text-white">Connexion</h5>
            <form class="space-y-6" method="post" action="{% url "members:login" %}">
                {% csrf_token %}
                <div>
                    <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">{{ form.username.label }}</label>
                    {% render_field form.username class+="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %}
                </div>
                <div>
                    <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">{{ form.password.label }}</label>
                    {% render_field form.password class+="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" %}
                </div>
                {% if form.errors %}
                    {% for key, value in form.errors.items %}
                        <div class="p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-100 dark:bg-gray-800 dark:text-red-400" role="alert">
                            <span class="font-medium">Erreur !</span> {{ key }} {{ value }}
                        </div>
                    {% endfor %}
                {% endif %}
                <div class="flex items-start">
                    <div class="flex items-start">
                        <div class="flex items-center h-5">
                            <input id="remember" type="checkbox" value="" class="w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-blue-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800" />
                        </div>
                        <label for="remember" class="ms-2 text-sm font-medium text-gray-900 dark:text-gray-300">Se souvenir de moi</label>
                    </div>
                    <a href="#" class="ms-auto text-sm text-blue-700 hover:underline dark:text-blue-500">Mot de passe oublié?</a>
                </div>
                <button type="submit" class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Se connecter</button>
                <div class="text-sm font-medium text-gray-500 dark:text-gray-300">
                    Pas de compte <a href="{% url "members:signup" %}" class="text-blue-700 hover:underline dark:text-blue-500">Créez un compte</a>
                </div>
            </form>
        </div>


    </div>
</section>
{% endblock content %}

templates/base.html
{% load compress %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

   
    <title>{% block title %} MCG | Welcome {% endblock title %}</title>
   

   <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>

    {% compress css %}
        <link rel="stylesheet" href="{% static 'assets/output.css' %}">
    {% endcompress %}

    <script defer type="module" src="{% static 'assets/flowbite.js' %}"></script>
    <script defer type="module" src="{% static 'assets/alpine.js' %}"></script>
    <script defer type="module" src="{% static 'assets/htmx.js' %}"></script>
    
</head>
    
<body>
    {% block header %}
    {% endblock header %}
      
    {% block content %}
    {% endblock content %}

    {% block footer %}
    {% endblock footer %}
 </body>
</html>